version: '3.8'

services:
  db:
    # Defines a name for your container rather than having docker create a random one for you
    container_name: mysql_local
    # Defines environment values to pass into the container.
    # The ${} values are being provided by the .env file
    environment:
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_USER: ${DB_USER}
    # The image from the docker repository to use when creating this container
    # Standard name:version format
    image: mysql:8.0.22
    # Defines the ports to bind the container to
    # HOST_MACHINE:CONTAINER
    ports:
      - 3306:3306
    # Will always attempt to restart the container if it stops for any reason
    restart: always
    # Mounts the internal /var/lib/mysql directory from within the container to the /db/data directory on the host machine
    # This allows us to start, stop, delete, and re-create the container and retain our information.
    volumes:
      - ./db/data:/var/lib/mysql
